/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JPRG_CA2_Project;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author ASUS
 */
public class StudentManagementView extends javax.swing.JFrame {

    private final StudentManagementController controller;
    
    /**
     * Creates new form StudentManagementView
     */
    public StudentManagementView() {
        initComponents();
        controller = new StudentManagementController(this);
        
        // Initially set to be un-editable
        textAreaForStudentResults.setEnabled(false);
        
        // - for adding module panel
        dropDownModuleCode.setEnabled(false);
        textFieldForStudentModuleMark.setEnabled(false);
        buttonForAddingModulesToStudent.setEnabled(false);
        
        // - deleting the student
        buttonForDeletingStudent.setEnabled(false);
        
        // listen to the window closing 'X'
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                controller.exitProgram();
                System.exit(0);
            }
        });
        
        // TEMPORARY DATA LOADING
        Map<String, List<HashMap<String, Object>>> classMapFromFile = FileManagement.readFromStudentFile("studentsInformation.txt");
        Student.setClassMap(classMapFromFile);
        Student.printClassMap();
        System.out.println("---------------------------------");
        
        HashMap<String, ArrayList<String>> studentModMapFromFile = FileManagement.readFromStudentModMapFile("studentModMapInformation.txt");
        Student.setStudentModMap(studentModMapFromFile);
        System.out.println(Student.getStudentModMap());
        
        System.out.println("---------------------------------");
    }

    // JOptaion Pane
    public void showJOptionDialog(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }
    
    public boolean showYesNoJOptionDialog(String message, String title) {
        boolean confirm = true;
        
        if (JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            return confirm;
        }
        else {
            return !confirm;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        mainMenuTabPane = new javax.swing.JTabbedPane();
        panelForStudents = new javax.swing.JPanel();
        studentLeftInfoContainer = new javax.swing.JPanel();
        panelForStudentInfoContainer_Students = new javax.swing.JPanel();
        labelForStudentName = new javax.swing.JLabel();
        labelForStudentAdmin = new javax.swing.JLabel();
        labelForStudentClass = new javax.swing.JLabel();
        buttonForCreatingStudent = new javax.swing.JButton();
        buttonForDeletingStudent = new javax.swing.JButton();
        textFieldForStudentName = new javax.swing.JTextField();
        textFieldForStudentAdmin = new javax.swing.JTextField();
        textFieldForStudentClass = new javax.swing.JTextField();
        panelForModuleInfoContainer_Students = new javax.swing.JPanel();
        labelForStudentModuleCode = new javax.swing.JLabel();
        labelForStudentModuleMark = new javax.swing.JLabel();
        textFieldForStudentModuleMark = new javax.swing.JTextField();
        buttonForAddingModulesToStudent = new javax.swing.JButton();
        dropDownModuleCode = new javax.swing.JComboBox<>();
        studentRightInfoContainer = new javax.swing.JPanel();
        panelForStudentSearchContainer = new javax.swing.JPanel();
        radioButtonForStudentClass = new javax.swing.JRadioButton();
        radioButtonForStudentAdmin = new javax.swing.JRadioButton();
        radioButtonForStudentName = new javax.swing.JRadioButton();
        buttonForSearchingStudents = new javax.swing.JButton();
        buttonForClearingSearchedStudents = new javax.swing.JButton();
        textFieldForSearchStudents = new javax.swing.JTextField();
        panelForStudentResultsContainer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaForStudentResults = new javax.swing.JTextArea();
        panelForStudentsExitButton = new javax.swing.JPanel();
        buttonForExitProgram_Students = new javax.swing.JButton();
        panelForModules = new javax.swing.JPanel();
        modulesLeftInfoContainer = new javax.swing.JPanel();
        panelForModuleInfoContainer_Modules = new javax.swing.JPanel();
        labelForModuleName = new javax.swing.JLabel();
        labelForModuleCode = new javax.swing.JLabel();
        labelForModuleCredit = new javax.swing.JLabel();
        textFieldForModuleName_Modules = new javax.swing.JTextField();
        textFieldForModuleCode = new javax.swing.JTextField();
        textFieldForModuleCredit = new javax.swing.JTextField();
        buttonForCreatingModule = new javax.swing.JButton();
        buttonForUpdatingModule = new javax.swing.JButton();
        buttonForDeletingModule = new javax.swing.JButton();
        labelForModulePrerequisite = new javax.swing.JLabel();
        comboBoxForModulePrerequisite = new javax.swing.JComboBox<>();
        modulesRigthInfoContainer = new javax.swing.JPanel();
        panelForModuleSearchContainer = new javax.swing.JPanel();
        radioButtonForModuleCode = new javax.swing.JRadioButton();
        radioButtonForModuleName = new javax.swing.JRadioButton();
        textFieldForSearchModules = new javax.swing.JTextField();
        buttonForSearchingModule = new javax.swing.JButton();
        buttonForClearingModuleSearch = new javax.swing.JButton();
        panelForModuleResultsContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelForModulesExitButton = new javax.swing.JPanel();
        buttonForExitProgram_Modules = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panelForStudents.setLayout(new javax.swing.BoxLayout(panelForStudents, javax.swing.BoxLayout.LINE_AXIS));

        studentLeftInfoContainer.setPreferredSize(new java.awt.Dimension(450, 446));
        studentLeftInfoContainer.setLayout(new java.awt.GridBagLayout());

        panelForStudentInfoContainer_Students.setBackground(new java.awt.Color(246, 246, 246));
        panelForStudentInfoContainer_Students.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelForStudentInfoContainer_Students.setForeground(new java.awt.Color(0, 0, 0));
        panelForStudentInfoContainer_Students.setLayout(new java.awt.GridBagLayout());

        labelForStudentName.setForeground(new java.awt.Color(0, 0, 0));
        labelForStudentName.setText("Name:");
        labelForStudentName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
        panelForStudentInfoContainer_Students.add(labelForStudentName, gridBagConstraints);

        labelForStudentAdmin.setForeground(new java.awt.Color(0, 0, 0));
        labelForStudentAdmin.setText("Admin:");
        labelForStudentAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        panelForStudentInfoContainer_Students.add(labelForStudentAdmin, gridBagConstraints);

        labelForStudentClass.setForeground(new java.awt.Color(0, 0, 0));
        labelForStudentClass.setText("Class:");
        labelForStudentClass.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        panelForStudentInfoContainer_Students.add(labelForStudentClass, gridBagConstraints);

        buttonForCreatingStudent.setBackground(new java.awt.Color(102, 102, 255));
        buttonForCreatingStudent.setText("Create");
        buttonForCreatingStudent.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonForCreatingStudent.setMargin(new java.awt.Insets(5, 20, 6, 20));
        buttonForCreatingStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForCreatingStudentActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 5);
        panelForStudentInfoContainer_Students.add(buttonForCreatingStudent, gridBagConstraints);

        buttonForDeletingStudent.setBackground(new java.awt.Color(246, 43, 43));
        buttonForDeletingStudent.setText("Delete");
        buttonForDeletingStudent.setMargin(new java.awt.Insets(5, 20, 6, 20));
        buttonForDeletingStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForDeletingStudentActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 15);
        panelForStudentInfoContainer_Students.add(buttonForDeletingStudent, gridBagConstraints);

        textFieldForStudentName.setBackground(new java.awt.Color(204, 204, 204));
        textFieldForStudentName.setForeground(new java.awt.Color(51, 51, 51));
        textFieldForStudentName.setText("Name");
        textFieldForStudentName.setMaximumSize(new java.awt.Dimension(2147483647, 35));
        textFieldForStudentName.setMinimumSize(new java.awt.Dimension(100, 22));
        textFieldForStudentName.setPreferredSize(new java.awt.Dimension(300, 35));
        textFieldForStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldForStudentNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 5, 15);
        panelForStudentInfoContainer_Students.add(textFieldForStudentName, gridBagConstraints);

        textFieldForStudentAdmin.setBackground(new java.awt.Color(204, 204, 204));
        textFieldForStudentAdmin.setForeground(new java.awt.Color(51, 51, 51));
        textFieldForStudentAdmin.setText("Admin");
        textFieldForStudentAdmin.setMinimumSize(new java.awt.Dimension(100, 22));
        textFieldForStudentAdmin.setPreferredSize(new java.awt.Dimension(300, 35));
        textFieldForStudentAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldForStudentAdminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        panelForStudentInfoContainer_Students.add(textFieldForStudentAdmin, gridBagConstraints);

        textFieldForStudentClass.setBackground(new java.awt.Color(204, 204, 204));
        textFieldForStudentClass.setForeground(new java.awt.Color(51, 51, 51));
        textFieldForStudentClass.setText("Class");
        textFieldForStudentClass.setMinimumSize(new java.awt.Dimension(100, 22));
        textFieldForStudentClass.setPreferredSize(new java.awt.Dimension(300, 35));
        textFieldForStudentClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldForStudentClassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        panelForStudentInfoContainer_Students.add(textFieldForStudentClass, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 5);
        studentLeftInfoContainer.add(panelForStudentInfoContainer_Students, gridBagConstraints);

        panelForModuleInfoContainer_Students.setBackground(new java.awt.Color(246, 246, 246));
        panelForModuleInfoContainer_Students.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Module", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelForModuleInfoContainer_Students.setLayout(new java.awt.GridBagLayout());

        labelForStudentModuleCode.setForeground(new java.awt.Color(0, 0, 0));
        labelForStudentModuleCode.setText("Module Code:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Students.add(labelForStudentModuleCode, gridBagConstraints);

        labelForStudentModuleMark.setForeground(new java.awt.Color(0, 0, 0));
        labelForStudentModuleMark.setText("Mark:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Students.add(labelForStudentModuleMark, gridBagConstraints);

        textFieldForStudentModuleMark.setBackground(new java.awt.Color(204, 204, 204));
        textFieldForStudentModuleMark.setForeground(new java.awt.Color(51, 51, 51));
        textFieldForStudentModuleMark.setText("Mark");
        textFieldForStudentModuleMark.setPreferredSize(new java.awt.Dimension(275, 35));
        textFieldForStudentModuleMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldForStudentModuleMarkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Students.add(textFieldForStudentModuleMark, gridBagConstraints);

        buttonForAddingModulesToStudent.setBackground(new java.awt.Color(102, 255, 102));
        buttonForAddingModulesToStudent.setForeground(new java.awt.Color(0, 0, 0));
        buttonForAddingModulesToStudent.setText("Add");
        buttonForAddingModulesToStudent.setMargin(new java.awt.Insets(5, 20, 6, 20));
        buttonForAddingModulesToStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForAddingModulesToStudentActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Students.add(buttonForAddingModulesToStudent, gridBagConstraints);

        dropDownModuleCode.setBackground(new java.awt.Color(204, 204, 204));
        dropDownModuleCode.setForeground(new java.awt.Color(51, 51, 51));
        dropDownModuleCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item1", "Item2" }));
        dropDownModuleCode.setPreferredSize(new java.awt.Dimension(275, 35));
        dropDownModuleCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownModuleCodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Students.add(dropDownModuleCode, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        studentLeftInfoContainer.add(panelForModuleInfoContainer_Students, gridBagConstraints);

        panelForStudents.add(studentLeftInfoContainer);

        studentRightInfoContainer.setMinimumSize(new java.awt.Dimension(300, 0));
        studentRightInfoContainer.setLayout(new java.awt.GridBagLayout());

        panelForStudentSearchContainer.setBackground(new java.awt.Color(246, 246, 246));
        panelForStudentSearchContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelForStudentSearchContainer.setMinimumSize(new java.awt.Dimension(20, 200));
        panelForStudentSearchContainer.setPreferredSize(new java.awt.Dimension(343, 200));
        panelForStudentSearchContainer.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(radioButtonForStudentClass);
        radioButtonForStudentClass.setForeground(new java.awt.Color(0, 0, 0));
        radioButtonForStudentClass.setText("Class");
        radioButtonForStudentClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonForStudentClassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 68);
        panelForStudentSearchContainer.add(radioButtonForStudentClass, gridBagConstraints);

        buttonGroup1.add(radioButtonForStudentAdmin);
        radioButtonForStudentAdmin.setForeground(new java.awt.Color(0, 0, 0));
        radioButtonForStudentAdmin.setText("Student By Admin");
        radioButtonForStudentAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonForStudentAdminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        panelForStudentSearchContainer.add(radioButtonForStudentAdmin, gridBagConstraints);

        buttonGroup1.add(radioButtonForStudentName);
        radioButtonForStudentName.setForeground(new java.awt.Color(0, 0, 0));
        radioButtonForStudentName.setText("Student By Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        panelForStudentSearchContainer.add(radioButtonForStudentName, gridBagConstraints);

        buttonForSearchingStudents.setBackground(new java.awt.Color(102, 102, 255));
        buttonForSearchingStudents.setText("Search");
        buttonForSearchingStudents.setMargin(new java.awt.Insets(5, 20, 6, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 10, 5);
        panelForStudentSearchContainer.add(buttonForSearchingStudents, gridBagConstraints);

        buttonForClearingSearchedStudents.setBackground(new java.awt.Color(255, 51, 51));
        buttonForClearingSearchedStudents.setText("Clear");
        buttonForClearingSearchedStudents.setMargin(new java.awt.Insets(5, 20, 6, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 15);
        panelForStudentSearchContainer.add(buttonForClearingSearchedStudents, gridBagConstraints);

        textFieldForSearchStudents.setBackground(new java.awt.Color(204, 204, 204));
        textFieldForSearchStudents.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        panelForStudentSearchContainer.add(textFieldForSearchStudents, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 10);
        studentRightInfoContainer.add(panelForStudentSearchContainer, gridBagConstraints);

        panelForStudentResultsContainer.setBackground(new java.awt.Color(246, 246, 246));
        panelForStudentResultsContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelForStudentResultsContainer.setToolTipText("");
        panelForStudentResultsContainer.setPreferredSize(new java.awt.Dimension(335, 250));

        textAreaForStudentResults.setBackground(new java.awt.Color(204, 204, 204));
        textAreaForStudentResults.setColumns(20);
        textAreaForStudentResults.setForeground(new java.awt.Color(0, 0, 0));
        textAreaForStudentResults.setRows(5);
        jScrollPane2.setViewportView(textAreaForStudentResults);

        javax.swing.GroupLayout panelForStudentResultsContainerLayout = new javax.swing.GroupLayout(panelForStudentResultsContainer);
        panelForStudentResultsContainer.setLayout(panelForStudentResultsContainerLayout);
        panelForStudentResultsContainerLayout.setHorizontalGroup(
            panelForStudentResultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelForStudentResultsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelForStudentResultsContainerLayout.setVerticalGroup(
            panelForStudentResultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelForStudentResultsContainerLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 1, 10);
        studentRightInfoContainer.add(panelForStudentResultsContainer, gridBagConstraints);

        panelForStudentsExitButton.setPreferredSize(new java.awt.Dimension(335, 40));

        buttonForExitProgram_Students.setBackground(new java.awt.Color(255, 0, 0));
        buttonForExitProgram_Students.setText("Exit");
        buttonForExitProgram_Students.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonForExitProgram_Students.setMargin(new java.awt.Insets(5, 20, 6, 20));
        buttonForExitProgram_Students.setPreferredSize(new java.awt.Dimension(65, 29));
        buttonForExitProgram_Students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForExitProgram_StudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelForStudentsExitButtonLayout = new javax.swing.GroupLayout(panelForStudentsExitButton);
        panelForStudentsExitButton.setLayout(panelForStudentsExitButtonLayout);
        panelForStudentsExitButtonLayout.setHorizontalGroup(
            panelForStudentsExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
            .addGroup(panelForStudentsExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelForStudentsExitButtonLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonForExitProgram_Students, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        panelForStudentsExitButtonLayout.setVerticalGroup(
            panelForStudentsExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(panelForStudentsExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelForStudentsExitButtonLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonForExitProgram_Students, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 5, 5, 10);
        studentRightInfoContainer.add(panelForStudentsExitButton, gridBagConstraints);

        panelForStudents.add(studentRightInfoContainer);

        mainMenuTabPane.addTab("Students", panelForStudents);

        panelForModules.setLayout(new javax.swing.BoxLayout(panelForModules, javax.swing.BoxLayout.LINE_AXIS));

        modulesLeftInfoContainer.setMinimumSize(new java.awt.Dimension(100, 555));
        modulesLeftInfoContainer.setPreferredSize(new java.awt.Dimension(450, 476));
        modulesLeftInfoContainer.setLayout(new java.awt.GridBagLayout());

        panelForModuleInfoContainer_Modules.setBackground(new java.awt.Color(246, 246, 246));
        panelForModuleInfoContainer_Modules.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Module", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelForModuleInfoContainer_Modules.setForeground(new java.awt.Color(0, 0, 0));
        panelForModuleInfoContainer_Modules.setPreferredSize(new java.awt.Dimension(350, 400));
        panelForModuleInfoContainer_Modules.setLayout(new java.awt.GridBagLayout());

        labelForModuleName.setForeground(new java.awt.Color(0, 0, 0));
        labelForModuleName.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(labelForModuleName, gridBagConstraints);

        labelForModuleCode.setForeground(new java.awt.Color(0, 0, 0));
        labelForModuleCode.setText("Code:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(labelForModuleCode, gridBagConstraints);

        labelForModuleCredit.setForeground(new java.awt.Color(0, 0, 0));
        labelForModuleCredit.setText("Credit:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(labelForModuleCredit, gridBagConstraints);

        textFieldForModuleName_Modules.setBackground(new java.awt.Color(204, 204, 204));
        textFieldForModuleName_Modules.setForeground(new java.awt.Color(51, 51, 51));
        textFieldForModuleName_Modules.setText("Name");
        textFieldForModuleName_Modules.setMaximumSize(new java.awt.Dimension(275, 35));
        textFieldForModuleName_Modules.setPreferredSize(new java.awt.Dimension(275, 35));
        textFieldForModuleName_Modules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldForModuleName_ModulesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(textFieldForModuleName_Modules, gridBagConstraints);

        textFieldForModuleCode.setBackground(new java.awt.Color(204, 204, 204));
        textFieldForModuleCode.setForeground(new java.awt.Color(51, 51, 51));
        textFieldForModuleCode.setText("Code");
        textFieldForModuleCode.setPreferredSize(new java.awt.Dimension(275, 35));
        textFieldForModuleCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldForModuleCodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(textFieldForModuleCode, gridBagConstraints);

        textFieldForModuleCredit.setBackground(new java.awt.Color(204, 204, 204));
        textFieldForModuleCredit.setForeground(new java.awt.Color(51, 51, 51));
        textFieldForModuleCredit.setText("Credit");
        textFieldForModuleCredit.setPreferredSize(new java.awt.Dimension(275, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(textFieldForModuleCredit, gridBagConstraints);

        buttonForCreatingModule.setBackground(new java.awt.Color(102, 102, 255));
        buttonForCreatingModule.setText("Create");
        buttonForCreatingModule.setMargin(new java.awt.Insets(5, 20, 6, 20));
        buttonForCreatingModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForCreatingModuleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(buttonForCreatingModule, gridBagConstraints);

        buttonForUpdatingModule.setBackground(new java.awt.Color(255, 255, 102));
        buttonForUpdatingModule.setForeground(new java.awt.Color(0, 0, 0));
        buttonForUpdatingModule.setText("Update");
        buttonForUpdatingModule.setMargin(new java.awt.Insets(5, 20, 6, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(buttonForUpdatingModule, gridBagConstraints);

        buttonForDeletingModule.setBackground(new java.awt.Color(255, 51, 51));
        buttonForDeletingModule.setText("Delete");
        buttonForDeletingModule.setMargin(new java.awt.Insets(5, 20, 6, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(buttonForDeletingModule, gridBagConstraints);

        labelForModulePrerequisite.setForeground(new java.awt.Color(0, 0, 0));
        labelForModulePrerequisite.setText("Prerequisite:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(labelForModulePrerequisite, gridBagConstraints);

        comboBoxForModulePrerequisite.setBackground(new java.awt.Color(204, 204, 204));
        comboBoxForModulePrerequisite.setForeground(new java.awt.Color(51, 51, 51));
        comboBoxForModulePrerequisite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Item1", "Item2", "Item3", " " }));
        comboBoxForModulePrerequisite.setPreferredSize(new java.awt.Dimension(275, 35));
        comboBoxForModulePrerequisite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxForModulePrerequisiteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForModuleInfoContainer_Modules.add(comboBoxForModulePrerequisite, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 5);
        modulesLeftInfoContainer.add(panelForModuleInfoContainer_Modules, gridBagConstraints);

        panelForModules.add(modulesLeftInfoContainer);

        modulesRigthInfoContainer.setPreferredSize(new java.awt.Dimension(360, 555));
        modulesRigthInfoContainer.setLayout(new java.awt.GridBagLayout());

        panelForModuleSearchContainer.setBackground(new java.awt.Color(246, 246, 246));
        panelForModuleSearchContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelForModuleSearchContainer.setForeground(new java.awt.Color(0, 0, 0));
        panelForModuleSearchContainer.setMinimumSize(new java.awt.Dimension(267, 200));
        panelForModuleSearchContainer.setPreferredSize(new java.awt.Dimension(342, 200));
        panelForModuleSearchContainer.setLayout(new java.awt.GridBagLayout());

        buttonGroup2.add(radioButtonForModuleCode);
        radioButtonForModuleCode.setForeground(new java.awt.Color(0, 0, 0));
        radioButtonForModuleCode.setText("Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
        panelForModuleSearchContainer.add(radioButtonForModuleCode, gridBagConstraints);

        buttonGroup2.add(radioButtonForModuleName);
        radioButtonForModuleName.setForeground(new java.awt.Color(0, 0, 0));
        radioButtonForModuleName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 5, 15);
        panelForModuleSearchContainer.add(radioButtonForModuleName, gridBagConstraints);

        textFieldForSearchModules.setBackground(new java.awt.Color(204, 204, 204));
        textFieldForSearchModules.setForeground(new java.awt.Color(204, 204, 204));
        textFieldForSearchModules.setPreferredSize(new java.awt.Dimension(275, 35));
        textFieldForSearchModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldForSearchModulesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        panelForModuleSearchContainer.add(textFieldForSearchModules, gridBagConstraints);

        buttonForSearchingModule.setBackground(new java.awt.Color(102, 102, 255));
        buttonForSearchingModule.setText("Search");
        buttonForSearchingModule.setMargin(new java.awt.Insets(5, 20, 6, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 5);
        panelForModuleSearchContainer.add(buttonForSearchingModule, gridBagConstraints);

        buttonForClearingModuleSearch.setBackground(new java.awt.Color(255, 51, 51));
        buttonForClearingModuleSearch.setText("Clear");
        buttonForClearingModuleSearch.setMargin(new java.awt.Insets(5, 20, 6, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 15);
        panelForModuleSearchContainer.add(buttonForClearingModuleSearch, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 10);
        modulesRigthInfoContainer.add(panelForModuleSearchContainer, gridBagConstraints);

        panelForModuleResultsContainer.setBackground(new java.awt.Color(246, 246, 246));
        panelForModuleResultsContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelForModuleResultsContainer.setForeground(new java.awt.Color(0, 0, 0));
        panelForModuleResultsContainer.setPreferredSize(new java.awt.Dimension(342, 275));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelForModuleResultsContainerLayout = new javax.swing.GroupLayout(panelForModuleResultsContainer);
        panelForModuleResultsContainer.setLayout(panelForModuleResultsContainerLayout);
        panelForModuleResultsContainerLayout.setHorizontalGroup(
            panelForModuleResultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelForModuleResultsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelForModuleResultsContainerLayout.setVerticalGroup(
            panelForModuleResultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelForModuleResultsContainerLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 1, 10);
        modulesRigthInfoContainer.add(panelForModuleResultsContainer, gridBagConstraints);

        panelForModulesExitButton.setPreferredSize(new java.awt.Dimension(347, 40));

        buttonForExitProgram_Modules.setBackground(new java.awt.Color(255, 0, 0));
        buttonForExitProgram_Modules.setText("Exit");
        buttonForExitProgram_Modules.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonForExitProgram_Modules.setMargin(new java.awt.Insets(5, 20, 6, 20));
        buttonForExitProgram_Modules.setMinimumSize(new java.awt.Dimension(65, 29));

        javax.swing.GroupLayout panelForModulesExitButtonLayout = new javax.swing.GroupLayout(panelForModulesExitButton);
        panelForModulesExitButton.setLayout(panelForModulesExitButtonLayout);
        panelForModulesExitButtonLayout.setHorizontalGroup(
            panelForModulesExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelForModulesExitButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonForExitProgram_Modules, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelForModulesExitButtonLayout.setVerticalGroup(
            panelForModulesExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelForModulesExitButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonForExitProgram_Modules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 5, 5, 10);
        modulesRigthInfoContainer.add(panelForModulesExitButton, gridBagConstraints);

        panelForModules.add(modulesRigthInfoContainer);

        mainMenuTabPane.addTab("Modules", panelForModules);

        jTabbedPane1.addTab("Admin", mainMenuTabPane);
        jTabbedPane1.addTab("Student", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldForStudentAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldForStudentAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldForStudentAdminActionPerformed

    private void buttonForExitProgram_StudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForExitProgram_StudentsActionPerformed
        // TODO add your handling code here:
        controller.exitProgram();
        System.exit(0);
    }//GEN-LAST:event_buttonForExitProgram_StudentsActionPerformed

    private void buttonForCreatingModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForCreatingModuleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonForCreatingModuleActionPerformed

    private void textFieldForModuleCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldForModuleCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldForModuleCodeActionPerformed

    private void comboBoxForModulePrerequisiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxForModulePrerequisiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxForModulePrerequisiteActionPerformed

    private void radioButtonForStudentClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonForStudentClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonForStudentClassActionPerformed

    private void textFieldForSearchModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldForSearchModulesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldForSearchModulesActionPerformed

    private void radioButtonForStudentAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonForStudentAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonForStudentAdminActionPerformed

    private void textFieldForModuleName_ModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldForModuleName_ModulesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldForModuleName_ModulesActionPerformed

    private void buttonForCreatingStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForCreatingStudentActionPerformed
        // TODO add your handling code here:
        // Gather all the Info Here
        String studentName = textFieldForStudentName.getText();
        String studentAdmin = textFieldForStudentAdmin.getText();
        String studentClass = textFieldForStudentClass.getText();
        HashMap<String, String> studentModules = new HashMap<>();
        
        // add student insided the classMap AND set up the dropdown box
        boolean result = controller.handleCreateStudentButtonClicked1(studentName, studentAdmin, studentClass, studentModules);
        
        if(result) {
            // populate the drop down box
            controller.addModulesInsideDropdownbox(studentAdmin, dropDownModuleCode);
            
            // set the textfields to non-editable
            textFieldForStudentName.setEnabled(false);
            textFieldForStudentAdmin.setEnabled(false);
            textFieldForStudentClass.setEnabled(false);

            // disable the create button
            buttonForCreatingStudent.setEnabled(false);
            
            // enable the delete button
            buttonForDeletingStudent.setEnabled(true);
            
            // enable to add modules
            dropDownModuleCode.setEnabled(true);
            textFieldForStudentModuleMark.setEnabled(true);
            buttonForAddingModulesToStudent.setEnabled(true);
        }
        
    }//GEN-LAST:event_buttonForCreatingStudentActionPerformed

    private void textFieldForStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldForStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldForStudentNameActionPerformed

    private void textFieldForStudentClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldForStudentClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldForStudentClassActionPerformed

    private void dropDownModuleCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownModuleCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropDownModuleCodeActionPerformed

    private void textFieldForStudentModuleMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldForStudentModuleMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldForStudentModuleMarkActionPerformed

    // ADD MODULE Button
    private void buttonForAddingModulesToStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForAddingModulesToStudentActionPerformed
        // TODO add your handling code here:
        // Gather all the info here
        String moduleMark = textFieldForStudentModuleMark.getText();
        String selectedModuleInput = (String) dropDownModuleCode.getSelectedItem();
        String studentAdminNumber = textFieldForStudentAdmin.getText();
        
        
        // give to controller to process further
        boolean result = controller.handleAddModuleButtonClicked(studentAdminNumber, moduleMark, selectedModuleInput);
        
        if(result) {
            // populate the drop down box
            controller.addModulesInsideDropdownbox(studentAdminNumber, dropDownModuleCode);
            
            // reset the dropbox, empty the textfield
            textFieldForStudentModuleMark.setText("");
            dropDownModuleCode.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_buttonForAddingModulesToStudentActionPerformed

    // DELETE STUDENT Button
    private void buttonForDeletingStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForDeletingStudentActionPerformed
        // TODO add your handling code here:
        // Gather all the info here
        String studentAdminNumber = textFieldForStudentAdmin.getText();
        
        // give to controller to handle
        boolean result = controller.handleDeleteStudentButtonClicked(studentAdminNumber);
        
        if(result) {
            // reset the textfields
            textFieldForStudentName.setEnabled(true);
            textFieldForStudentAdmin.setEnabled(true);
            textFieldForStudentClass.setEnabled(true);
            
            // reset clickables
            textFieldForStudentName.setText("");
            textFieldForStudentAdmin.setText("");
            textFieldForStudentClass.setText("");
            textFieldForStudentModuleMark.setEnabled(false);
            dropDownModuleCode.setEnabled(false);
            buttonForCreatingStudent.setEnabled(true);
            buttonForDeletingStudent.setEnabled(false);
            buttonForAddingModulesToStudent.setEnabled(false);
            
            // reset the dropdown box for adding modules
            controller.resetDropDownBox(dropDownModuleCode);
        }
    }//GEN-LAST:event_buttonForDeletingStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagementView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonForAddingModulesToStudent;
    private javax.swing.JButton buttonForClearingModuleSearch;
    private javax.swing.JButton buttonForClearingSearchedStudents;
    private javax.swing.JButton buttonForCreatingModule;
    private javax.swing.JButton buttonForCreatingStudent;
    private javax.swing.JButton buttonForDeletingModule;
    private javax.swing.JButton buttonForDeletingStudent;
    private javax.swing.JButton buttonForExitProgram_Modules;
    private javax.swing.JButton buttonForExitProgram_Students;
    private javax.swing.JButton buttonForSearchingModule;
    private javax.swing.JButton buttonForSearchingStudents;
    private javax.swing.JButton buttonForUpdatingModule;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboBoxForModulePrerequisite;
    private javax.swing.JComboBox<String> dropDownModuleCode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelForModuleCode;
    private javax.swing.JLabel labelForModuleCredit;
    private javax.swing.JLabel labelForModuleName;
    private javax.swing.JLabel labelForModulePrerequisite;
    private javax.swing.JLabel labelForStudentAdmin;
    private javax.swing.JLabel labelForStudentClass;
    private javax.swing.JLabel labelForStudentModuleCode;
    private javax.swing.JLabel labelForStudentModuleMark;
    private javax.swing.JLabel labelForStudentName;
    private javax.swing.JTabbedPane mainMenuTabPane;
    private javax.swing.JPanel modulesLeftInfoContainer;
    private javax.swing.JPanel modulesRigthInfoContainer;
    private javax.swing.JPanel panelForModuleInfoContainer_Modules;
    private javax.swing.JPanel panelForModuleInfoContainer_Students;
    private javax.swing.JPanel panelForModuleResultsContainer;
    private javax.swing.JPanel panelForModuleSearchContainer;
    private javax.swing.JPanel panelForModules;
    private javax.swing.JPanel panelForModulesExitButton;
    private javax.swing.JPanel panelForStudentInfoContainer_Students;
    private javax.swing.JPanel panelForStudentResultsContainer;
    private javax.swing.JPanel panelForStudentSearchContainer;
    private javax.swing.JPanel panelForStudents;
    private javax.swing.JPanel panelForStudentsExitButton;
    private javax.swing.JRadioButton radioButtonForModuleCode;
    private javax.swing.JRadioButton radioButtonForModuleName;
    private javax.swing.JRadioButton radioButtonForStudentAdmin;
    private javax.swing.JRadioButton radioButtonForStudentClass;
    private javax.swing.JRadioButton radioButtonForStudentName;
    private javax.swing.JPanel studentLeftInfoContainer;
    private javax.swing.JPanel studentRightInfoContainer;
    private javax.swing.JTextArea textAreaForStudentResults;
    private javax.swing.JTextField textFieldForModuleCode;
    private javax.swing.JTextField textFieldForModuleCredit;
    private javax.swing.JTextField textFieldForModuleName_Modules;
    private javax.swing.JTextField textFieldForSearchModules;
    private javax.swing.JTextField textFieldForSearchStudents;
    private javax.swing.JTextField textFieldForStudentAdmin;
    private javax.swing.JTextField textFieldForStudentClass;
    private javax.swing.JTextField textFieldForStudentModuleMark;
    private javax.swing.JTextField textFieldForStudentName;
    // End of variables declaration//GEN-END:variables
}
